apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dreamscape

resources:
- deployment.yaml
- service.yaml
- pvc.yaml
- configmap.yaml
- networkpolicy.yaml

labels:
- pairs:
    app: redis
    component: cache
    part-of: dreamscape
