apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: user-service-base

resources:
- deployment.yaml
- service.yaml

labels:
- pairs:
    app.kubernetes.io/name: user-service
    app.kubernetes.io/component: user
    app.kubernetes.io/part-of: dreamscape

images:
- name: ghcr.io/dreamscape/user
  newTag: latest
