apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: common-resources

resources:
- cert-issuer.yaml

labels:
- pairs:
    app.kubernetes.io/part-of: dreamscape
    app.kubernetes.io/component: common
