apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: voyage-service-base

resources:
- deployment.yaml
- service.yaml

labels:
- pairs:
    app.kubernetes.io/name: voyage-service
    app.kubernetes.io/component: voyage
    app.kubernetes.io/part-of: dreamscape

images:
- name: ghcr.io/dreamscape/voyage
  newTag: latest
