apiVersion: v1
kind: Service
metadata:
  name: voyage-service
  labels:
    app: voyage-service
    component: voyage
    part-of: dreamscape
spec:
  type: ClusterIP
  selector:
    app: voyage-service
  ports:
  - name: http
    port: 3003
    targetPort: 3003
    protocol: TCP
