apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: gateway-service-base

resources:
- deployment.yaml
- service.yaml
- ingress.yaml
- configmap.yaml
- hpa.yaml
- networkpolicy.yaml
- poddisruptionbudget.yaml

labels:
- pairs:
    app.kubernetes.io/name: gateway-service
    app.kubernetes.io/component: gateway
    app.kubernetes.io/part-of: dreamscape

images:
- name: ghcr.io/dreamscape/gateway
  newTag: latest